/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import Clases.Conexion;
import Clases.Trabajador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class ModificarTrabajador extends javax.swing.JFrame {
    private Conexion c=new Conexion();
    /**
     * Creates new form ModificarTrabajador
     */
    public ModificarTrabajador() {
        initComponents();
        setLocationRelativeTo(this);
        construircboRut();
        construircboCargo();
        deshabilitar();
        construircboCiudad();
        
    }
    
    public void construircboRut(){
        DefaultComboBoxModel cbo=c.construirComboBox("trabajador","rut_tra");
        cbo_MRut.setModel(cbo);
    }

    public void construircboCiudad(){
        DefaultComboBoxModel cbo2=c.construirComboBox("ciudad", "nom_ciu");
        cbo_MCiudad.setModel(cbo2);
    }
    
    public void construircboCargo(){
        DefaultComboBoxModel cbo3=c.construirComboBox("cargo", "nom_car");
        cbo_MCargo.setModel(cbo3);
    }
    
    public void limpiarFormulario(){
        cbo_MRut.setSelectedIndex(0);
        txt_MNombre.setText("");
        txt_MDireccion.setText("");
        txt_MSueldoBase.setText("");
        cbo_MCiudad.setSelectedIndex(0);
        cbo_MCargo.setSelectedIndex(0);
        mGrupoSexo.clearSelection();
    }
    
    public void modificarTrabajador(){
        Trabajador tra=new Trabajador();
        String rut =cbo_MRut.getSelectedItem().toString();
        tra.setNombre(txt_MNombre.getText());
        tra.setDireccion(txt_MDireccion.getText());
        tra.setCiudad(cbo_MCiudad.getSelectedIndex());
        if(rbtn_MMasculino.isSelected()){
            tra.setSexo("Masculino");
        }else{
            tra.setSexo("Femenino");
        }
        tra.setCargo(cbo_MCargo.getSelectedIndex());
        tra.setSueldoBase(txt_MSueldoBase.getText());
        c.modificarTrabajador(tra,rut);
        limpiarFormulario();
        construircboRut();
    }
    
    public void deshabilitar(){
        cbo_MRut.setEnabled(true);
        txt_MNombre.setEnabled(false);
        txt_MDireccion.setEnabled(false);
        txt_MSueldoBase.setEnabled(false);
        cbo_MCiudad.setEnabled(false);
        cbo_MCargo.setEnabled(false);
        rbtn_MMasculino.setEnabled(false);
        rbtn_MFemenino.setEnabled(false);
        
    }
    
    public void habilitar(){
        txt_MNombre.setEnabled(true);
        txt_MDireccion.setEnabled(true);
        txt_MSueldoBase.setEnabled(true);
        cbo_MCiudad.setEnabled(true);
        cbo_MCargo.setEnabled(true);
        rbtn_MMasculino.setEnabled(true);
        rbtn_MFemenino.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mGrupoSexo = new javax.swing.ButtonGroup();
        btn_MModificarTrabajador = new javax.swing.JButton();
        btn_MLimpiarFormulario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_MRut = new javax.swing.JComboBox<>();
        txt_MSueldoBase = new javax.swing.JTextField();
        cbo_MCargo = new javax.swing.JComboBox<>();
        rbtn_MMasculino = new javax.swing.JRadioButton();
        rbtn_MFemenino = new javax.swing.JRadioButton();
        txt_MDireccion = new javax.swing.JTextField();
        txt_MNombre = new javax.swing.JTextField();
        cbo_MCiudad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_MModificarTrabajador.setText("Modificar Trabajador");
        btn_MModificarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MModificarTrabajadorActionPerformed(evt);
            }
        });

        btn_MLimpiarFormulario.setText("Limpiar Formulario");
        btn_MLimpiarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MLimpiarFormularioActionPerformed(evt);
            }
        });

        jLabel1.setText("Rut:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Ciudad:");

        jLabel5.setText("Sexo:");

        jLabel6.setText("Cargo:");

        jLabel7.setText("Sueldo Base");

        cbo_MRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_MRutActionPerformed(evt);
            }
        });

        mGrupoSexo.add(rbtn_MMasculino);
        rbtn_MMasculino.setText("Masculino");

        mGrupoSexo.add(rbtn_MFemenino);
        rbtn_MFemenino.setText("Femenino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(cbo_MRut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_MModificarTrabajador))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_MMasculino)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_MLimpiarFormulario)
                                    .addComponent(rbtn_MFemenino)))
                            .addComponent(cbo_MCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_MSueldoBase)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbo_MCiudad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_MDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MNombre))
                                .addGap(108, 108, 108)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_MRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_MDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_MCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtn_MMasculino)
                        .addComponent(rbtn_MFemenino)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cbo_MCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txt_MSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_MModificarTrabajador)
                    .addComponent(btn_MLimpiarFormulario))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MLimpiarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MLimpiarFormularioActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btn_MLimpiarFormularioActionPerformed

    private void btn_MModificarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MModificarTrabajadorActionPerformed
        modificarTrabajador();
    }//GEN-LAST:event_btn_MModificarTrabajadorActionPerformed

    private void cbo_MRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_MRutActionPerformed
        String buscarRut=cbo_MRut.getSelectedItem().toString();
        Trabajador borrador=c.mostrarTrabajador(buscarRut);
        txt_MNombre.setText(borrador.getNombre());
        txt_MDireccion.setText(borrador.getDireccion());
        txt_MSueldoBase.setText(borrador.getSueldoBase());
        cbo_MCiudad.setSelectedIndex(borrador.getCiudad());
        cbo_MCargo.setSelectedIndex(borrador.getCargo());
        if(borrador.getSexo().equalsIgnoreCase("Masculino")){
                rbtn_MMasculino.setSelected(true);
            }else{
                rbtn_MFemenino.setSelected(true);
            }
        habilitar();
        
    }//GEN-LAST:event_cbo_MRutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MLimpiarFormulario;
    private javax.swing.JButton btn_MModificarTrabajador;
    private javax.swing.JComboBox<String> cbo_MCargo;
    private javax.swing.JComboBox<String> cbo_MCiudad;
    private javax.swing.JComboBox<String> cbo_MRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.ButtonGroup mGrupoSexo;
    private javax.swing.JRadioButton rbtn_MFemenino;
    private javax.swing.JRadioButton rbtn_MMasculino;
    private javax.swing.JTextField txt_MDireccion;
    private javax.swing.JTextField txt_MNombre;
    private javax.swing.JTextField txt_MSueldoBase;
    // End of variables declaration//GEN-END:variables
}
