/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_AdminTrabajadores = new javax.swing.JMenu();
        mit_GuardarT = new javax.swing.JMenuItem();
        mit_ModificarT = new javax.swing.JMenuItem();
        mit_EliminarT = new javax.swing.JMenuItem();
        mn_AdminAplicacion = new javax.swing.JMenu();
        mit_AdminPermisos = new javax.swing.JMenuItem();
        mit_AdminCiudades = new javax.swing.JMenuItem();
        mit_AdminCargos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        mn_AdminTrabajadores.setText("Administrar trabajadores");

        mit_GuardarT.setText("Añadir Trabajador");
        mit_GuardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_GuardarTActionPerformed(evt);
            }
        });
        mn_AdminTrabajadores.add(mit_GuardarT);

        mit_ModificarT.setText("Modificar Trabajador");
        mit_ModificarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_ModificarTActionPerformed(evt);
            }
        });
        mn_AdminTrabajadores.add(mit_ModificarT);

        mit_EliminarT.setText("EliminarTrabajador");
        mit_EliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_EliminarTActionPerformed(evt);
            }
        });
        mn_AdminTrabajadores.add(mit_EliminarT);

        jMenuBar1.add(mn_AdminTrabajadores);

        mn_AdminAplicacion.setText("Administrar aplicación");

        mit_AdminPermisos.setText("Administrar Permisos");
        mit_AdminPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_AdminPermisosActionPerformed(evt);
            }
        });
        mn_AdminAplicacion.add(mit_AdminPermisos);

        mit_AdminCiudades.setText("Administrar Ciudades");
        mit_AdminCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_AdminCiudadesActionPerformed(evt);
            }
        });
        mn_AdminAplicacion.add(mit_AdminCiudades);

        mit_AdminCargos.setText("Administrar Cargos");
        mit_AdminCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_AdminCargosActionPerformed(evt);
            }
        });
        mn_AdminAplicacion.add(mit_AdminCargos);

        jMenuBar1.add(mn_AdminAplicacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mit_GuardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_GuardarTActionPerformed
        new IngresoTrabajador().setVisible(true);
    }//GEN-LAST:event_mit_GuardarTActionPerformed

    private void mit_EliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_EliminarTActionPerformed
        new EliminarTrabajador().setVisible(true);
    }//GEN-LAST:event_mit_EliminarTActionPerformed

    private void mit_AdminPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_AdminPermisosActionPerformed
        new AdministrarUsuario().setVisible(true);
    }//GEN-LAST:event_mit_AdminPermisosActionPerformed

    private void mit_ModificarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_ModificarTActionPerformed
        new ModificarTrabajador().setVisible(true);
    }//GEN-LAST:event_mit_ModificarTActionPerformed

    private void mit_AdminCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_AdminCiudadesActionPerformed
        new AdministrarCiudades().setVisible(true);
    }//GEN-LAST:event_mit_AdminCiudadesActionPerformed

    private void mit_AdminCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_AdminCargosActionPerformed
        new AdministrarCargos().setVisible(true);
    }//GEN-LAST:event_mit_AdminCargosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mit_AdminCargos;
    private javax.swing.JMenuItem mit_AdminCiudades;
    private javax.swing.JMenuItem mit_AdminPermisos;
    private javax.swing.JMenuItem mit_EliminarT;
    private javax.swing.JMenuItem mit_GuardarT;
    private javax.swing.JMenuItem mit_ModificarT;
    private javax.swing.JMenu mn_AdminAplicacion;
    private javax.swing.JMenu mn_AdminTrabajadores;
    // End of variables declaration//GEN-END:variables
}
